version: "3"
services:
  dash-docker:
    image: snehilvj/dash-docker:0.1.0
    depends_on:
      - redis

  redis:
    image: redis:alpine

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
