version: "3"
services:
  dash-docker:
    build:
      context: .
      args:
        - POETRY_VERSION=1.1.13
        - DASH_PORT=8050
    depends_on:
      - redis
    volumes:
      - ./:/app:ro

  redis:
    image: redis:alpine

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3000:80
